#!/bin/bash
#pip install -r requirements.txt
TARGET_DIR=/usr/local/monetax-cron
echo "Copying all necessary files into target directory . . ."
mkdir -p $TARGET_DIR
mkdir -p $TARGET_DIR/log
mkdir -p /usr/local/bin
chmod -R 755 $TARGET_DIR
cp -r src $TARGET_DIR/src
cp env.example $TARGET_DIR/.env
cp monetax_cron.py $TARGET_DIR
ln -s $TARGET_DIR/monetax_cron.py /usr/bin/monetax_cron
